apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: 5001

          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MONGODB_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: JWT_SECRET
