apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MONGODB_ROOT_USERNAME: {{ .Values.secrets.mongodbUsername | quote }}
  MONGODB_ROOT_PASSWORD: {{ .Values.secrets.mongodbPassword | quote }}
  MONGODB_URI: {{ .Values.secrets.mongodbUri | quote }}
